[project]
name = "revbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "accelerate>=1.12.0",
  "bitsandbytes",
  "datasets==4.3.0",
  "hf-transfer>=0.1.9",
  "marimo>=0.18.2",
  "nbformat>=5.10.4",
  "peft>=0.17.1",
  "pytorch-triton-rocm>=3.4.0",
  "torch==2.9.0",
  "torchao>=0.13.0",
  "torchvision>=0.23.0",
  "transformers>=4.57.1",
  "trl>=0.25.1",
  "xformers>=0.0.32.post2",
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.4"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-rocm" },
]
torchvision = [
  { index = "pytorch-rocm" },
]
pytorch-triton-rocm = [
  { index = "pytorch-rocm" },
]
xformers = [
  { index = "pytorch-rocm" },
]
bitsandbytes = { workspace = true }

[tool.uv.workspace]
members = [
    "bitsandbytes",
]
